#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Ulauncher border=false
bspc rule -a firefox desktop=2
bspc rule -a Org.gnome.Nautilus desktop=3
bpsc rule -a vlc desktop=5
bspc rule -a Pavucontrol desktop=6
bspc rule -a Lxappearance desktop=6
bspc rule -a qt5ct desktop=6

feh --bg-scale ~/圖片/wallpapers/bg_15.jpg

picom --config ~/dotfiles/picom.conf &

~/.config/polybar/docky/launch.sh

# resume previous screen condition
val=$(cat ~/.warm-screen) 
if [ "$val" = "true" ]; then
	sct 4500
fi

xsetroot -cursor_name left_ptr &

fcitx5 &

bspc config focused_border_color "#41ab88"

xrdb ~/.Xresources

ulauncher --hide-window &
